version: "3.7"
services:
  app:
    build:
      args:
        user: user
      context: ./
      dockerfile: Dockerfile
    image: php
    container_name: thanos-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php:/usr/local/etc/php/conf.d
    networks:
      - mynetwork

  db:
    image: mariadb:latest
    ports:
      - "33060:3306"
    container_name: thanos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: thanos-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - mynetwork

  redis:
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge